### PR TITLE
Update Python SDK docs for public release

### PR DESCRIPTION
**Pull request by carolstran**
### Description

We're preparing to release the Python SDK (aka publicly announce it via a blog post) and some of the existing documentation needed to be updated 🐍 

What was updated ✨ 
- Removed any "alpha" references
- Mention that it's open source and include GitHub link
- Other small clean ups based on updates to the internal SDK repo docs

### Additional context

Related internal ticket 🎫  [SDOCS-7](https://emnify.atlassian.net/browse/SDOCS-7)

[SDOCS-7]: https://emnify.atlassian.net/browse/SDOCS-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by techwriter-dev — CHANGES_REQUESTED** [review]
## Urgent change required!

The link to the application token guide will do more harm than good.

outdated-token-how-to

This needs to be changed:

python-sdk-urgent-change-required

To use the Python SDK, you need to create an application token.
You can do this by navigating to the [Integrations](https://portal.emnify.com/integrations) section of the emnify Portal and scrolling down a few pages until you see the **Application Tokens** section:
portal-integrations-app-tokens-add-token

```
To use the Python SDK, you need to create an application token.
You can do this by navigating to the [Integrations](https://portal.emnify.com/integrations)section of the emnify Portal and scrolling down a few pages until you see the **Application Tokens** section:
```

In addition to the `portal-integrations-app-tokens-add-token.png` screenshot above, I created 3 other screenshots to be included in a new how-to for creating application tokens using the new portal.

I suggest we open a new issue for replacing the outdated one: 
https://www.emnify.com/developer-blog/how-to-use-an-application-token-for-api-authentication

**Comment by carolstran** [comment]
@techwriter-dev Regarding the application token guide, I definitely agree this should be updated, but I would consider this out of scope for this specific PR (as the main goal is to remove the "alpha" reference and I didn't touch the text you're referring to). If you could open a new PR with the changes you suggested, that'd be excellent 🙌🏼 

I'll apply the other suggestions and ping for a re-review 😊

**Comment by carolstran** [comment]
@techwriter-dev Ready for re-review!

**Comment by techwriter-dev** [comment]
> @techwriter-dev Regarding the application token guide, I definitely agree this should be updated, but I would consider this out of scope for this specific PR (as the main goal is to remove the "alpha" reference and I didn't touch the text you're referring to). If you could open a new PR with the changes you suggested, that'd be excellent 🙌🏼

Created internal 🎫 [SDOCS-253](https://emnify.atlassian.net/browse/SDOCS-253) since this entails the migration of external content to our docs, which other pages will be referencing.

**Review by techwriter-dev — APPROVED** [review]
Within the original scope of the PR, the changes look good.

**Pull request merged**
